### ISSUE TITLE
Multiple Accounts shown together in Device View

### ISSUE THREAD

**Issue by c7274864** [YorkshireIoT/ha-google-fit#109]
### System Health details

Good morning
what's the point of having several Google Fit accounts, but all the sensors of "X" accounts are in the same window, I don't find that interesting or logical

![Capture d'écran 2023-09-30 205415](https://github.com/YorkshireIoT/ha-google-fit/assets/143031506/805bc645-2c96-4cb8-90b1-eb2afd4b054e)
![Capture d'écran 2023-09-30 205114](https://github.com/YorkshireIoT/ha-google-fit/assets/143031506/afd65b95-0478-475f-8d7f-805c5bcee2ed)

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/YorkshireIoT/ha-google-fit/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

what's the point of having several Google Fit accounts, but all the sensors of "X" accounts are in the same window, I don't find that interesting or logical

### Reproduction steps

what's the point of having several Google Fit accounts, but all the sensors of "X" accounts are in the same window, I don't find that interesting or logical

### Debug logs

```text
what's the point of having several Google Fit accounts, but all the sensors of "X" accounts are in the same window, I don't find that interesting or logical
```

**Comment by YorkshireIoT** [comment]
@c7274864, I've no idea why this is happening and it isn't the expected behaviour. I suspect it's something to do with the device ID's not being unique enough so HA groups everything together.
