### ISSUE TITLE
Fitbit data in Google Fit

### ISSUE THREAD

**Issue by deepcoder** [YorkshireIoT/ha-google-fit#124]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/YorkshireIoT/ha-google-fit/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Not sure if you have any information on this, however I would appreciate any insights you might have.

I've converted a Fitbit account over to Google, using their method. However, I was expecting the Fitbit data to automagically appear in the Google Fit world.  But no. I've tried a bit of 'googling' however, other than using an Android app to connect the two (not an option as user is an iOS Fitbit user), I have found no information on how Fitbit data will appear in the Google world after converting the account.

Thanks for info and your work on this Home Assistant useful addon.

### Describe the solution you'd like

.....

### Describe alternatives you've considered

.....

### Additional context

.....

**Comment by YorkshireIoT** [comment]
Hi @deepcoder, sorry I don't have much experience with either iOS data conversion or Fitbit. I do know there's a good app called Health Sync (for Android) which can sync data across different health data providers, but I'm not sure that would be much use in your case.

There's a native [Fitbit](https://www.home-assistant.io/integrations/fitbit/) integration in Home Assistant if you just want your health data in HA though?
