### ISSUE TITLE
Error when trying to add the sensor

### ISSUE THREAD

**Issue by it-e4e** [YorkshireIoT/ha-google-fit#130]
### Describe the issue

I've followed all the steps in the tutorial, but in the last part when the device is being added, home assistant returns an error.

### Debug logs

```text
Este error se originó a partir de una integración personalizada.

Logger: googleapiclient.http
Source: custom_components/google_fit/config_flow.py:86
Integration: google_fit (documentation, issues)
First occurred: 11:39:09 (2 occurrences)
Last logged: 13:14:53

Sleeping 1.19 seconds before retry 1 of 1 for request: GET https://www.googleapis.com/discovery/v1/apis/fitness/v1/rest, after The read operation timed out
Sleeping 1.88 seconds before retry 1 of 1 for request: GET https://www.googleapis.com/discovery/v1/apis/fitness/v1/rest, after The read operation timed out
```

![image](https://github.com/YorkshireIoT/ha-google-fit/assets/40636437/fcb833fe-0222-41b6-b586-37fa26f76086)
![image](https://github.com/YorkshireIoT/ha-google-fit/assets/40636437/70e501fb-d082-44cb-859c-bc871ec34d3e)
![image](https://github.com/YorkshireIoT/ha-google-fit/assets/40636437/1385a3fc-82c5-431c-b09b-79c2ed6032af)
![image](https://github.com/YorkshireIoT/ha-google-fit/assets/40636437/c0d4cda8-7e99-437a-9c57-ad0bacd31b65)
![image](https://github.com/YorkshireIoT/ha-google-fit/assets/40636437/4a0ff937-99ff-4840-96e5-dc7272b1c465)
![image](https://github.com/YorkshireIoT/ha-google-fit/assets/40636437/26f4dd4b-537a-463d-8e61-aac86b427cbc)
![image](https://github.com/YorkshireIoT/ha-google-fit/assets/40636437/f0efa4ec-7ae1-45cf-abbc-184c1a440aae)
![image](https://github.com/YorkshireIoT/ha-google-fit/assets/40636437/e473ba0a-d251-4651-a04a-9c6a9702636b)

I'm desperate, thank you

**Comment by YorkshireIoT** [comment]
Hi @it-e4e, from the log it's saying there is a timeout in the operation. This might have been a temporary problem with the Google servers, or something on your end. Have you tried again since?

**Comment by YorkshireIoT** [comment]
Closing this down @it-e4e. If you try again, and it's still a problem please re-open
