### ISSUE TITLE
Can't add integration

### ISSUE THREAD

**Issue by meyerdominik** [YorkshireIoT/ha-google-fit#132]
## System Information

version | core-2023.10.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.5
os_name | Linux
os_version | 6.1.21-v8
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4986
Installed Version | 1.33.0
Stage | running
Available Repositories | 1328
Downloaded Repositories | 8

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 44

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.1
-- | --
update_channel | stable
supervisor_version | supervisor-2023.11.0
agent_version | 1.6.0
docker_version | 24.0.6
disk_total | 57.8 GB
disk_used | 6.8 GB
healthy | true
supported | true
board | rpi3-64
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.6.0), NGINX Home Assistant SSL proxy (3.5.0), Let's Encrypt (4.12.9), Samba share (11.0.0), Terminal & SSH (9.8.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 1
views | 6
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | November 4, 2023 at 08:52
-- | --
current_recorder_run | November 9, 2023 at 16:27
estimated_db_size | 173.76 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/YorkshireIoT/ha-google-fit/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

I'm getting the following error, whenever I'm trying to add the integration:

![image](https://github.com/YorkshireIoT/ha-google-fit/assets/9396465/cdd80f60-5c01-4910-9ac4-e2fcac22e7fd)

`Config flow could not be loaded: <html> <head><title>504 Gateway Time-out</title></head> <body> <center><h1>504 Gateway Time-out</h1></center> <hr><center>nginx</center> </body> </html> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page -->`

### Reproduction steps

1. Download integration through HACS
2. Restart HA
3. Settings -> Devices & Services
4. \+ ADD INTEGRATION
5. Select "Google Fit"

### Debug logs

```text
2023-11-11 21:46:14.070 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [547456376512] Dominik from XX.XXX.XXX.XX (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36): Sending [{"id":137,"type":"result","success":true,"result":{"resources":{"component.google_fit.config.abort.already_configured":"Account is already configured","component.google_fit.config.abort.already_in_progress":"Configuration flow is already in progress","component.google_fit.config.abort.access_error":"Fit API Access error:\n{reason}\nAborting setup.","component.google_fit.config.abort.cannot_connect":"Failed to connect","component.google_fit.config.abort.code_expired":"Authentication code expired or credential setup is invalid, please try again.","component.google_fit.config.abort.invalid_access_token":"Invalid access token","component.google_fit.config.abort.missing_configuration":"The component is not configured. Please follow the documentation.","component.google_fit.config.abort.oauth_error":"Received invalid token data.","component.google_fit.config.abort.reauth_successful":"Re-authentication was successful","component.google_fit.config.abort.timeout_connect":"Timeout establishing connection","component.google_fit.config.create_entry.default":"Successfully authenticated","component.google_fit.config.step.auth.title":"Link Google Account","component.google_fit.config.step.pick_implementation.title":"Pick Authentication Method","component.google_fit.config.step.reauth_confirm.description":"The Google Fit integration needs to re-authenticate your account","component.google_fit.config.step.reauth_confirm.title":"Reauthenticate Integration"}}},{"id":138,"type":"result","success":true,"result":{"resources":{}}}]
```

**Comment by YorkshireIoT** [comment]
Hi @meyerdominik, I haven't been able to replicate this issue (it looks like it might be related to #130).

Could you try again and attach the full debug logs please? The one above is just a single timestamp

**Comment by meyerdominik** [comment]
Well, I can't really do that. I'd have to upload my full debug logs of all of homeassistant. 
Is there another way, that I'm not aware of?

**Comment by YorkshireIoT** [comment]
Depending on how comfortable you are with regex it'd be pretty easy to filter using the component tag `custom_components.google_fit`.

If not, if you could just find the exact lines around when the integration fails that should also work

**Comment by meyerdominik** [comment]
Here is every line that includes an `google_fit` with 

```
logger:
  default: debug
```

- 2023-11-14 18:00:27.756 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration google_fit which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
- 2023-11-14 18:03:56.850 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [548188371648] Dominik from 93.238.XXX.XXX (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36): Sending {"id":280,"type":"result","success":true,"result":{"core":{"integration":[...]"google_fit":{"config_flow":true,"integration_type":"hub","iot_class":"cloud_polling","name":"Google Fit"}},"helper":{}}}}
- 2023-11-14 18:03:56.850 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [548188371648] Dominik from 93.238.XXX.XXX (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36): Sending {"id":280,"type":"result","success":true,"result":{"id": 280,"type": "result","success": true,"result": {[...]"custom": {"integration": {[...]"google_fit": {"config_flow": true,"integration_type": "hub","iot_class": "cloud_polling","name": "Google Fit"}},"helper": {}}}}}
- 2023-11-14 18:03:59.423 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [548188371648] Dominik from 93.238.XXX.XXX (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36): Sending {"id":282,"type":"result","success":true,"result":{"domain":"google_fit","name":"Google Fit","codeowners":["@YorkshireIoT"],"config_flow":true,"dependencies":["application_credentials"],"documentation":"https://github.com/YorkshireIoT/ha-google-fit","iot_class":"cloud_polling","issue_tracker":"https://github.com/YorkshireIoT/ha-google-fit/issues","requirements":["oauth2client==4.1.3","google-api-python-client==2.82.0"],"version":"v2.1.2","is_built_in":false}}

I don't unterstand. I'm not even getting the error from my initial comment.. I did the exact same steps as before and the issue still persists.

**Comment by YorkshireIoT** [comment]
> Here is every line that includes an `google_fit` with
> 
> ```
> logger:
>   default: debug
> ```
> 
>     * 2023-11-14 18:00:27.756 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration google_fit which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
> 
>     * 2023-11-14 18:03:56.850 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [548188371648] Dominik from 93.238.XXX.XXX (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36): Sending {"id":280,"type":"result","success":true,"result":{"core":{"integration":[...]"google_fit":{"config_flow":true,"integration_type":"hub","iot_class":"cloud_polling","name":"Google Fit"}},"helper":{}}}}
> 
>     * 2023-11-14 18:03:56.850 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [548188371648] Dominik from 93.238.XXX.XXX (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36): Sending {"id":280,"type":"result","success":true,"result":{"id": 280,"type": "result","success": true,"result": {[...]"custom": {"integration": {[...]"google_fit": {"config_flow": true,"integration_type": "hub","iot_class": "cloud_polling","name": "Google Fit"}},"helper": {}}}}}
> 
>     * 2023-11-14 18:03:59.423 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [548188371648] Dominik from 93.238.XXX.XXX (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36): Sending {"id":282,"type":"result","success":true,"result":{"domain":"google_fit","name":"Google Fit","codeowners":["@YorkshireIoT"],"config_flow":true,"dependencies":["application_credentials"],"documentation":"[https://github.com/YorkshireIoT/ha-google-fit","iot_class":"cloud_polling","issue_tracker":"https://github.com/YorkshireIoT/ha-google-fit/issues","requirements":["oauth2client==4.1.3","google-api-python-client==2.82.0"],"version":"v2.1.2","is_built_in":false}}](https://github.com/YorkshireIoT/ha-google-fit%22,%22iot_class%22:%22cloud_polling%22,%22issue_tracker%22:%22https://github.com/YorkshireIoT/ha-google-fit/issues%22,%22requirements%22:%5B%22oauth2client==4.1.3%22,%22google-api-python-client==2.82.0%22%5D,%22version%22:%22v2.1.2%22,%22is_built_in%22:false%7D%7D)
> 
> 
> I don't unterstand. I'm not even getting the error from my initial comment.. I did the exact same steps as before and the issue still persists.

I don't think this is the issue but you seem to be on the latest version of this integration `v2.1.2` but it says you're using an older version of the Google API client `2.82.0` when the version specified should be `2.107.0` [requirements.txt](https://github.com/YorkshireIoT/ha-google-fit/blob/main/requirements.txt#L5C27-L5C34).

Could you remove the integration, any credentials you've configured, re-install the integration and try again please just to see if this will force a reinstall of the requirements?

**Comment by meyerdominik** [comment]
I didn't configure any google fit credentials (I have some configured for other google integrations). So I just removed the integration via HACS, reinstalled it via HACS, restarted homeassistant and tried setting up the integration. 

Sadly, the same error appeared.

**Comment by meyerdominik** [comment]
Thanks. Here are the logs. The one with `component.google_fit.config.abort.already_configured` stood out to me. Especially since I didn't ever configure the integration..

Here is a screenshot of my application credentials:
![Untitled](https://github.com/YorkshireIoT/ha-google-fit/assets/9396465/ac31e898-53c4-421c-93ab-63a0ed7c8874)

- 2023-11-29 16:37:28.567 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [548038986560] Dominik from XX.XXX.XXX.XXX (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36): Received {'type': 'manifest/get', 'integration': 'google_fit', 'id': 350}
- 2023-11-29 16:37:28.568 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [548038986560] Dominik from XX.XXX.XXX.XXX (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36): Sending {"id":350,"type":"result","success":true,"result":{"domain":"google_fit","name":"Google Fit","codeowners":["@YorkshireIoT"],"config_flow":true,"dependencies":["application_credentials"],"documentation":"https://github.com/YorkshireIoT/ha-google-fit","iot_class":"cloud_polling","issue_tracker":"https://github.com/YorkshireIoT/ha-google-fit/issues","requirements":["oauth2client==4.1.3","google-api-python-client==2.82.0"],"version":"v3.0.0","is_built_in":false}}
- 2023-11-29 16:37:28.582 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [548038986560] Dominik from XX.XXX.XXX.XXX (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36): Received {'type': 'frontend/get_translations', 'language': 'en', 'category': 'config', 'integration': ['google_fit'], 'id': 351}
- 2023-11-29 16:37:28.584 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [548038986560] Dominik from XX.XXX.XXX.XXX (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36): Received {'type': 'frontend/get_translations', 'language': 'en', 'category': 'selector', 'integration': ['google_fit'], 'id': 352}
- 2023-11-29 16:37:28.585 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [548038986560] Dominik from XX.XXX.XXX.XXX (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36): Received {'type': 'frontend/get_translations', 'language': 'en', 'category': 'title', 'integration': ['google_fit'], 'id': 353}
- 2023-11-29 16:37:28.586 DEBUG (MainThread) [homeassistant.helpers.translation] Cache miss for en: google_fit
- 2023-11-29 16:37:28.605 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [548038986560] Dominik from XX.XXX.XXX.XXX (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36): Sending [{"id":351,"type":"result","success":true,"result":{"resources":{"component.google_fit.config.abort.already_configured":"Account is already configured","component.google_fit.config.abort.already_in_progress":"Configuration flow is already in progress","component.google_fit.config.abort.access_error":"Fit API Access error:\n{reason}\nAborting setup.","component.google_fit.config.abort.cannot_connect":"Failed to connect","component.google_fit.config.abort.code_expired":"Authentication code expired or credential setup is invalid, please try again.","component.google_fit.config.abort.invalid_access_token":"Invalid access token","component.google_fit.config.abort.missing_configuration":"The component is not configured. Please follow the documentation.","component.google_fit.config.abort.oauth_error":"Received invalid token data.","component.google_fit.config.abort.reauth_successful":"Re-authentication was successful","component.google_fit.config.abort.timeout_connect":"Timeout establishing connection","component.google_fit.config.create_entry.default":"Successfully authenticated","component.google_fit.config.step.auth.title":"Link Google Account","component.google_fit.config.step.pick_implementation.title":"Pick Authentication Method","component.google_fit.config.step.reauth_confirm.description":"The Google Fit integration needs to re-authenticate your account","component.google_fit.config.step.reauth_confirm.title":"Reauthenticate Integration"}}},{"id":352,"type":"result","success":true,"result":{"resources":{}}}]
- 2023-11-29 16:37:28.618 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [548038986560] Dominik from XX.XXX.XXX.XXX (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36): Sending {"id":353,"type":"result","success":true,"result":{"resources":{"component.google_fit.title":"Google Fit"}}}

**Comment by YorkshireIoT** [comment]
Looking at those logs, it never even gets to the integration as the first thing that does is send a debug log.

Can you look at two of the solutions suggested [here](https://community.home-assistant.io/t/hacs-installing-problem-via-integration-error-config-flow-could-not-be-loaded/314501/15?page=2):
* Using local IP when adding the configuraiton
* Try remove an integration like Google Cast, hard reboot of the host, add back Google Cast and then try add Google Fit again

**Comment by meyerdominik** [comment]
> Using local IP when adding the configuraiton

This worked. Thanks for your help, @YorkshireIoT!
