### ISSUE TITLE
Add sensor blood pressure and pulse

### ISSUE THREAD

**Issue by rafkan20** [YorkshireIoT/ha-google-fit#14]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/YorkshireIoT/ha-google-fit/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Please add blood pressure and heart rate sensor.

### Describe the solution you'd like

The google fit app has blood pressure and heart rate readings.

### Describe alternatives you've considered

Lack

### Additional context

Lack

**Comment by YorkshireIoT** [comment]
Hi @rafkan20,

I'd like to understand a bit more about what you'd like to see here before I add it.

This integration is limited by one main thing:
- The rate data is updated by Google is very slow (30 minutes to 1 hour). This means even though the integration will poll much quicker than this it is as slow as the weakest link.

That means you're not going to see a nice continuous graph with lots of points on it for something like heart rate. I'm not just how useful a heart rate reading every 30-60 minutes really is.

Blood Pressure is a bit different as this is more stable and something you might want to track over time.

With this in mind I can suggest a few options for this:

- Just upload the latest heart rate/blood pressure reading, meaning a handful of readings every hour
- Add a new "average" sensor. This could average more points over the last 1 hour or 24 hours. 
- Add new minimum + maximum sensors, once again looking at the last hour or day.

What sort of use case are you looking at using this data for?

**Comment by YorkshireIoT** [comment]
Would require new scopes:
- `https://www.googleapis.com/auth/fitness.blood_pressure.read`
- `https://www.googleapis.com/auth/fitness.heart_rate.read`

**Comment by YorkshireIoT** [comment]
See:
- https://developers.google.com/fit/datatypes/health#heart_rate
- https://developers.google.com/fit/datatypes/health#blood_pressure

**Comment by rafkan20** [comment]
So it is possible to add these sensors? I am asking as a layman.

**Comment by rafkan20** [comment]
> Yes, sorry it's possible. Working on it now. Was just adding info for my own benefit

Cool thanks
