### ISSUE TITLE
Unit in Kwh instead of meter, points, steps

### ISSUE THREAD

**Issue by Merangle** [YorkshireIoT/ha-google-fit#142]
## System Information

version | core-2023.11.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.59
arch | aarch64
timezone | Europe/Paris
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.33.0
Stage | running
Available Repositories | 1348
Downloaded Repositories | 29

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.1
-- | --
update_channel | stable
supervisor_version | supervisor-2023.11.3
agent_version | 1.6.0
docker_version | 24.0.6
disk_total | 27.9 GB
disk_used | 15.4 GB
healthy | true
supported | true
board | odroid-n2
supervisor_api | ok
version_api | ok
installed_addons | Samba share (12.1.0), Samba Backup (5.2.0), Grafana (9.1.1), Mosquitto broker (6.4.0), Terminal & SSH (9.8.1), Spotify Connect (0.12.6), Studio Code Server (5.14.2), ESPHome (2023.11.4), Network UPS Tools (0.12.2), Z-Wave JS (0.4.1), Wmbusmeters (W-MBus to MQTT) (1.12.0), Piper (1.4.0), Music Assistant BETA (2.0.0b75), Zigbee2MQTT (1.33.2-1), Whisper (1.0.0), openWakeWord (1.8.2), ZeroTier One (0.17.3), MariaDB (2.6.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 18
views | 22
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | November 22, 2023 at 20:05
-- | --
current_recorder_run | November 25, 2023 at 16:55
estimated_db_size | 967.42 MiB
database_engine | mysql
database_version | 10.6.12

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/YorkshireIoT/ha-google-fit/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

The card displays wrong unit for the data:

- steps in kWh
- Distance in kWh
- heart point in kWh
- calories in kWh
- active minutes in kWh

![fit](https://github.com/YorkshireIoT/ha-google-fit/assets/19497834/7bf3643d-e131-4a77-b48a-ed1b63f0301e)

Any idea what must be changed ?
There is no posibilty to modify at entity level.
Regards

### Reproduction steps

1.
2.
3.
...
d

### Debug logs

```text
d
```

**Comment by YorkshireIoT** [comment]
Hi @Merangle, I can't replicate this issue with the latest version. What version are you on? That also doesn't look like the stock HA device information page. Could you send a screenshot of that page as well please?

**Comment by Merangle** [comment]
hello

here are the requested screenshots
Regards

Le dim. 26 nov. 2023 à 12:16, YorkshireIoT ***@***.***> a
écrit :

**Comment by YorkshireIoT** [comment]
Closing this issue down due to lack of information. Please re-open if it's still a problem
