### ISSUE TITLE
Ability to add a second Google Fit account

### ISSUE THREAD

**Issue by rafkan20** [YorkshireIoT/ha-google-fit#17]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/YorkshireIoT/ha-google-fit/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Please add the possibility of adding a second Google Fit account to the integration. So that my wife can also track her Home Assistant activity.

### Describe the solution you'd like

N/A

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by YorkshireIoT** [comment]
This should be possible, as it has been done for the Google Calendar component. See:
https://github.com/home-assistant/core/pull/73715

**Comment by rafkan20** [comment]
It will be great if you can do that.

**Comment by YorkshireIoT** [comment]
Just an update on this, the focus at the moment is making sure all the extra betas I've done are stable enough for a general release.

This will then be a focus for the next release after that

**Comment by YorkshireIoT** [comment]
Hi @rafkan20 , turns out the integration could always have multiple accounts you just have to go through a fairly unintuive setup process to get there. I've updated the README and you can find more information on how to do this here:
https://github.com/YorkshireIoT/ha-google-fit#adding-multiple-accounts

**Comment by rafkan20** [comment]
Hi @YorkshireIoT, thank you for adding this option to your integration.
