### ISSUE TITLE
Entity sensor.sleep from integration google_fit has state class total_increasing, but its state is negative

### ISSUE THREAD

**Issue by Bastian007** [YorkshireIoT/ha-google-fit#194]
## System Information

version | core-2024.2.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.1
os_name | Linux
os_version | 6.1.63-haos-raspi
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4280
Installed Version | 1.34.0
Stage | running
Available Repositories | 1470
Downloaded Repositories | 65

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | September 3, 2024 at 02:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | false
remote_server | eu-central-1-1.ui.nabu.casa
certificate_status | ready
instance_id | f814e3a29adc4a89ae7929ef13283cb9
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.5
-- | --
update_channel | stable
supervisor_version | supervisor-2024.01.1
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 457.7 GB
disk_used | 50.4 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Mosquitto broker (6.4.0), Samba share (12.3.0), Home Assistant Google Drive Backup (0.112.1), Studio Code Server (5.15.0), RaspberryMatic CCU (3.73.9.20240130), AppDaemon (0.16.4), PS5 MQTT (1.3.3), Zigbee2MQTT (1.35.3-1), MQTT Explorer (browser-1.0.1), Advanced SSH & Web Terminal (17.1.0), ZigStar TI CC2652P/P7 FW Flasher (0.4.0), Govee to MQTT Bridge (2024.01.24-ea3cd430), ESPHome (2023.12.9), Vcontrol add-on (1.10.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 38
views | 34
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | February 6, 2024 at 19:52
-- | --
current_recorder_run | February 16, 2024 at 09:44
estimated_db_size | 2210.98 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I have enabled debug logging for my installation and pasted in the debug logs below.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/YorkshireIoT/ha-google-fit/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Logger: homeassistant.components.sensor.recorder
Source: components/sensor/recorder.py:324
Integration: Sensor (documentation, issues)
First occurred: 09:47:37 (1 occurrences)
Last logged: 09:47:37

Entity sensor.sleep from integration google_fit has state class total_increasing, but its state is negative. Triggered by state -1680.0 with last_updated set to 2024-02-16T08:39:59.999999+00:00. Please create a bug report at https://github.com/YorkshireIoT/ha-google-fit/issues

### Integration Version

v4.0.0

### Reproduction steps

1. restart HA
2. HA Log shows the message above

### Debug logs

```text
log to big
```

**Comment by YorkshireIoT** [comment]
@Bastian007 - could you attach the history for the `sensor.sleep` and `sensor.awake_time` for a few hours eitherside of when you got the log message?

**Comment by Bastian007** [comment]
Sure, since two weeks I have not anymore that issue, however, the history log shows the issue:
![image](https://github.com/YorkshireIoT/ha-google-fit/assets/12425311/7f6fe155-a076-487d-b142-4384732890ba)
