### ISSUE TITLE
Add Hydration Details 

### ISSUE THREAD

**Issue by sarthakbis** [YorkshireIoT/ha-google-fit#20]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/YorkshireIoT/ha-google-fit/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Hydration data from Google Fit is not available

### Describe the solution you'd like

Please add Hydration data. It is available under Nutrition.

### Describe alternatives you've considered

Did not find alternatives

### Additional context

no other context

**Comment by YorkshireIoT** [comment]
Would require new scope: `https://www.googleapis.com/auth/fitness.nutrition.read`

Info here: https://developers.google.com/fit/datatypes/nutrition#hydration

**Comment by YorkshireIoT** [comment]
Hi @sarthakbis , there's a beta out for this now if you want to give it a go before the main release.

I don't use hydration in Google Fit at all, so if you've got any feedback please create new issue(s). Thanks 😄

**Comment by sarthakbis** [comment]
Thank you, will check it out

**Comment by sarthakbis** [comment]
Works perfectly. Thanks!!
