### ISSUE TITLE
Access blocked: authorization error

### ISSUE THREAD

**Issue by MagdalenaRyba** [YorkshireIoT/ha-google-fit#205]
### System Health details

  1

### Checklist

- [X] I have enabled debug logging for my installation and pasted in the debug logs below.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/YorkshireIoT/ha-google-fit/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Hi, I made a mistake when entering the API key and from now on there is no way to correct it. After redirecting to the authorization page, the message "Access blocked: authorization error" keeps popping up.
How to solve this problem?

### Integration Version

1

### Reproduction steps

1.
2.
3.

### Debug logs

```text
1
```

**Comment by YorkshireIoT** [comment]
Please see this section of the README: https://github.com/YorkshireIoT/ha-google-fit?tab=readme-ov-file#reconfiguring-badly-configured-credentials
