### ISSUE TITLE
Errore 400: redirect_uri_mismatch

### ISSUE THREAD

**Issue by doublec1973** [YorkshireIoT/ha-google-fit#222]
### System Health details

Access blocked: This app's request is invalid

You can't sign in because this app sent an invalid request. You can try again later or contact the developer to resolve the issue.
If you are a developer of this app, see the error details.
Error 400: redirect_uri_mismatch

### Checklist

- [X] I have enabled debug logging for my installation and pasted in the debug logs below.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/YorkshireIoT/ha-google-fit/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Access blocked: This app's request is invalid

You can't sign in because this app sent an invalid request. You can try again later or contact the developer to resolve the issue.
If you are a developer of this app, see the error details.
Error 400: redirect_uri_mismatch

### Integration Version

v4.0.0

### Reproduction steps

1.add credential
2.error
3.

### Debug logs

```text
no
```

**Comment by YorkshireIoT** [comment]
Hi @doublec1973,

Can you see if this applicable: https://github.com/YorkshireIoT/ha-google-fit/discussions/174?
This is almost down to something be incorrectly configured, so if the above doesn't fix it for you can you go through the instructions again and follow them exactly.

Thanks

**Comment by YorkshireIoT** [comment]
Closing this issue now as I can't replicate it. If it's still an issue after following the above steps above @doublec1973, please re-open.
