### ISSUE TITLE
cannot import name 'UnitOfTime' from 'homeassistant.const'

### ISSUE THREAD

**Issue by baronov** [YorkshireIoT/ha-google-fit#25]
### System Health details

core-2022.12.1
FreeBSD 13.1
Python - 3.9.15

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/YorkshireIoT/ha-google-fit/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Can't Install manually added component with  error 
"cannot import name 'UnitOfTime' from 'homeassistant.const'"

### Reproduction steps

Using the tool of choice open the directory (folder) for your HA configuration (where you find configuration.yaml).
If you do not have a custom_components directory (folder) there, you need to create it.
In the custom_components directory (folder) create a new folder called google_fit.
Download all the files from the custom_components/google_fit/ directory (folder) in this repository.
Place the files you downloaded in the new directory (folder) you created.
Restart Home Assistant
In the HA UI go to "Configuration" -> "Integrations" click "+" and search for "Google Fit"

### Debug logs

```text
2023-04-17 14:56:27.870 INFO (SyncWorker_0) [homeassistant.util.package] Attempting install of google-api-python-client==2.82.0
2023-04-17 14:56:36.459 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration google_fit: cannot import name 'UnitOfTime' from 'homeassistant.const' (/srv/homeassistant/lib/python3.9/site-packages/homeassistant/const.py)
```

**Comment by YorkshireIoT** [comment]
Hi @baronov,

This is caused by an update in the 2023.1 Core HA update. You can see more here:
https://developers.home-assistant.io/blog/2022/12/05/more-unit-enumerators/

You'll need at least 2023.1 and I'd recommend 2023.3 as that what the development has been done against
