### ISSUE TITLE
After Reboot or Update

### ISSUE THREAD

**Issue by milandzuris** [YorkshireIoT/ha-google-fit#26]
### System Health details

After Reboot or Update HA need again reconfigure Google Account, how fix this?

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/YorkshireIoT/ha-google-fit/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

*

### Reproduction steps

*

### Debug logs

```text
*
```

**Comment by YorkshireIoT** [comment]
Hi @milandzuris,

Can you add some more infomation like logs and whether it's happening on every reboot?

I haven't been able to reproduce this myself and no reconfiguration is required when I update or reboot

**Comment by milandzuris** [comment]
Log:

This error originated from a custom integration.

Logger: googleapiclient.http
Source: custom_components/google_fit/coordinator.py:107
Integration: Google Fit (documentation, issues)
First occurred: 20:55:05 (1 occurrences)
Last logged: 20:55:05

Encountered 403 Forbidden with reason "forbidden"



Logger: homeassistant.config_entries
Source: config_entries.py:407
First occurred: 20:55:05 (1 occurrences)
Last logged: 20:55:05

Config entry 'Google Fit' for google_fit integration could not authenticate: OAuth session is not valid, re-authentication required.

**Comment by milandzuris** [comment]
same after beta update to 2.3

**Comment by YorkshireIoT** [comment]
Can you do the following please:

> Make sure any existing Google Fit custom integrations have been removed from HACs.
> Remove any YAML configuration for Google Fit
> Remove *this* integration in HACs, restart HA and add it back again in HACs.
> Enable debug logging for the component in your configuration.yaml (see https://www.home-assistant.io/integrations/logger/)
> Restart Home Assistant and retry configuration.

If you have any issues can you attach the logs and send a screenshot of your configuration error in the UI

**Comment by milandzuris** [comment]
> Hi @milandzuris, can you report back with more info about the above steps if it didn't work or if it did, can you mark this issue as closed please?

Nothing new same problem give some time.

**Comment by YorkshireIoT** [comment]
> whats the shortcut for google fit?, is that good? ![image](https://user-images.githubusercontent.com/42905545/238206110-f5808c12-9a62-42c4-8a87-64022f8c5253.png) @YorkshireIoT

You will need to have something like this in your configuration.yaml
```
logger:
  default: info
  logs:
    custom_components.google_fit: debug
```

**Comment by YorkshireIoT** [comment]
It's now been over a month with no response. Closing this issue down.

Please comment on this explaining why it is still and issue and I'll reopen.

**Comment by loryanstrant** [comment]
Just saw this old thread, it's still an issue for me. :-(

**Comment by milandzuris** [comment]
> Just saw this old thread, it's still an issue for me. :-(

same

**Comment by YorkshireIoT** [comment]
Hi @loryanstrant and @milandzuris,

Can you make sure you're on the latest version, enable debug logging (see above), and report back with steps to reproduce and also the logs please?

Thanks

**Comment by milandzuris** [comment]
> Hi @loryanstrant and @milandzuris,
> 
> Can you make sure you're on the latest version, enable debug logging (see above), and report back with steps to reproduce and also the logs please?
> 
> Thanks

This problem it is somewhere else i think in Google account settings maybe🤷‍♂️, same problem for Tasks.

**Comment by pantherale0** [comment]
@YorkshireIoT same issue here, will enable debug on my dev instance and see whats happening :+1:

**Comment by milandzuris** [comment]
> @YorkshireIoT same issue here, will enable debug on my dev instance and see whats happening 👍

in debug there is nothing

**Comment by milandzuris** [comment]
i think this problem is in the google account settings same problem i have for Google Tasks

**Comment by YorkshireIoT** [comment]
Can I check you both have your **Publishing status** set to **Production** in your Google API credential settings?

**Comment by YorkshireIoT** [comment]
> > @YorkshireIoT same issue here, will enable debug on my dev instance and see whats happening 👍
> 
> in debug there is nothing

There is a lot of new debug logging at integration initialisation and startup added in a recent version. This doesn't really sound like an integration issue to me though.

**Comment by milandzuris** [comment]
> Can I check you both have your **Publishing status** set to **Production** in your Google API credential settings?

sorry where?, screenshot pls thx

**Comment by milandzuris** [comment]
> Can I check you both have your **Publishing status** set to **Production** in your Google API credential settings?

this?
![image](https://github.com/YorkshireIoT/ha-google-fit/assets/42905545/11a277a6-80ec-4191-a693-8b7bbf1e33dd)

**Comment by pantherale0** [comment]
Mine is set to testing, however I'm using the same project that I use for the other Home Assistant Google OAuth services like Nest with no issues.

**Comment by loryanstrant** [comment]
Mine was set to testing, as I wasn't sure how to set it to production without verifying it.

**Comment by YorkshireIoT** [comment]
@pantherale0 - the [Home Assistant docs for Google Mail](https://www.home-assistant.io/integrations/google_mail/) (which this repository duplicates for authentication) are pretty clear that it should be set to production otherwise you'll have to reauth every week. Can I ask that you try using **In Production** and see if that fixes your issue?

**Comment by YorkshireIoT** [comment]
> Mine was set to testing, as I wasn't sure how to set it to production without verifying it.

@loryanstrant - There should be no need for verification for this kind of app so you should just be able to set it to **In Production** without doing anything extra.

**Comment by YorkshireIoT** [comment]
@milandzuris - that's right. Could you add your debug logs at integration startup please? You can just do (all through the UI):
1. On the Integration page click *Enable debug logging*
![image](https://github.com/YorkshireIoT/ha-google-fit/assets/55233103/4c941b03-5489-4f08-80ea-c7de2ba025eb)
1. Click the 3 dots and then *Reload*
1. Click *Disable Debug Logging* and your log should download. Then just attach all the lines with `custom_components.google_fit`

Also, let me know if the auth is succesful or not.

**Comment by milandzuris** [comment]
> set to **Production** in your Google API

This fix my Problem

**Comment by loryanstrant** [comment]
Sorry forgot to respond. After setting it to production I no longer have the issue.
Thanks!
