### ISSUE TITLE
Sleep data goes to 0

### ISSUE THREAD

**Issue by crstian19** [YorkshireIoT/ha-google-fit#33]
## System Information

version | core-2023.4.5
-- | --
installation_type | Unknown
dev | false
hassio | false
docker | false
user | root
virtualenv | false
python_version | 3.10.10
os_name | Linux
os_version | 6.2.9
arch | x86_64
timezone | Europe/Madrid
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4968
Installed Version | 1.32.1
Stage | running
Available Repositories | 1272
Downloaded Repositories | 16

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 9
views | 6
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | April 15, 2023 at 10:24 AM
-- | --
current_recorder_run | April 18, 2023 at 11:29 PM
estimated_db_size | 123.88 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/YorkshireIoT/ha-google-fit/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

I have been using the integration for a few days and for the "Sleep data" part it is not working properly, as you can see in the picture, it writes 0 constantly.

Also I think too many requests are made to the Fitness API and we may get banned.

![image](https://user-images.githubusercontent.com/21632768/233597414-702c5601-8878-4764-bbdc-bae84cd21455.png)

Last 7 days total of requests 
![image](https://user-images.githubusercontent.com/21632768/233596700-33d47287-9b4b-4b2c-be8e-5db0ebfeeea1.png)

### Reproduction steps

Watch sleep data panel

### Debug logs

```text
No
```

**Comment by YorkshireIoT** [comment]
Hi @crstian19 ,

I've changed this issue so it just focuses on only one issue.
I haven't seen this in my own install, so I can't reproduce it.
Would you be able to attach the extra debug logging from the sensor at the points when the sleep data hits 0? It might provide some insight in to what's going on?

R.e. the too many requests to the API issue:
This is something I've been thinking about. I went to check out the quotas and usage on my own account and for me at least I don't think I'll ever be getting near the limit, even with an update interval of 1 minute:
![image](https://user-images.githubusercontent.com/55233103/233790120-133f5c2a-d1e3-4e1d-b22f-e029477ed2d0.png)

However, I realise their limit may not be the same as mine for whatever reason. I've added to new issues to make the update interval configurable: #35 and #36

**Comment by crstian19** [comment]
Can you explain me how to show that extra debug of the sensor?


> Hi @crstian19 ,
> 
> I've changed this issue so it just focuses on only one issue. I haven't seen this in my own install, so I can't reproduce it. Would you be able to attach the extra debug logging from the sensor at the points when the sleep data hits 0? It might provide some insight in to what's going on?
> 
> R.e. the too many requests to the API issue: This is something I've been thinking about. I went to check out the quotas and usage on my own account and for me at least I don't think I'll ever be getting near the limit, even with an update interval of 1 minute: ![image](https://user-images.githubusercontent.com/55233103/233790120-133f5c2a-d1e3-4e1d-b22f-e029477ed2d0.png)
> 
> However, I realise their limit may not be the same as mine for whatever reason. I've added to new issues to make the update interval configurable: #35 and #36

Can you explain me how to show that extra debug of the sensor?

**Comment by YorkshireIoT** [comment]
Hi @crstian19, are you still having issues with sleep data going to 0?

**Comment by YorkshireIoT** [comment]
Thanks for all the info @crstian19 but I still can't figure it out from that.

I've pushed up a new release (v0.3.1) with a bunch of extra debug logging when there's no sensor data, or it is 0. Would you mind updating and posting your logs again? Thanks

**Comment by YorkshireIoT** [comment]
It's now been over a month with no response. Closing this issue down.

Please comment on this explaining why it is still and issue and I'll reopen.
