### ISSUE TITLE
Add sensor - total number of steps.

### ISSUE THREAD

**Issue by rafkan20** [YorkshireIoT/ha-google-fit#34]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/YorkshireIoT/ha-google-fit/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Thank you @YorkshireIoT for adding the sensor blood pressure and pulse.
I have another request - you can add a total number of steps sensor, so that it does not delete once a day.
Based on it, you will be able to create a monthly number of steps, a yearly number of steps.

### Describe the solution you'd like

N/A

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by YorkshireIoT** [comment]
Hi @rafkan20 ,

I have something similar on my own install just through creating a new input number helper and then using an automation to add the current steps at 23:55 every day.

Adding this into the integration would lead to more code bloat, more API requests, slower update time and a marginally higher CPU + network usage.

I think on balance this is something better done outside the integration in the way described above.

If you would like a more detailed explanation of how to do this within Home Assistant, let me know
