### ISSUE TITLE
Error 400: redirect url mismatch

### ISSUE THREAD

**Issue by Ivesvdf** [YorkshireIoT/ha-google-fit#41]
## System Information

version | core-2023.4.4
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.10.10
os_name | Linux
os_version | 5.10.175-3.ph4
arch | x86_64
timezone | Europe/Brussels
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4194
Installed Version | 1.32.1
Stage | running
Available Repositories | 1273
Downloaded Repositories | 13

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 7
-- | --
resources | 3
views | 9
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | April 14, 2023 at 18:51
-- | --
current_recorder_run | April 24, 2023 at 11:01
estimated_db_size | 306.36 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

<details><summary>Solcast PV Forecast</summary>

can_reach_server | ok
-- | --
remaining_requests | 10
rooftop_site_count | 2
polling_hours | 6 -> 21 and once at midnight

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/YorkshireIoT/ha-google-fit/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

When adding the integration after entering the client id and token I'm redirected to a google page which shows 400: redirect url mismatch. 

I'm not sure how to retry - restarting HA does not reprompt for credentials. Uninstalling and reinstalling the plugin does not reprompt for credentials. 
![image](https://user-images.githubusercontent.com/264447/233952778-0b8defa6-cadb-40cd-9ab4-35c3ff144863.png)

### Reproduction steps

1. Add custom repo in HACS
2. Add integration 
3. Fill in credentials
4. Go to next step 
...

### Debug logs

```text
No
```

**Comment by YorkshireIoT** [comment]
Hi @Ivesvdf

Could you post a screenshot of what the credentials page on your Google API cloud account looks like (with you client ID + secret hidden)?

**Comment by Ivesvdf** [comment]
Hi, I see what you're getting at ;-). You're right I did it wrong, I should have picked web app and not Tv and limited input (like I would for google calendar). I'm guessing that'll be the issue. 

Do you have a tip on how to make the HA system forget about the credentials I provided? Uninstalling and reinstalling the integration does not seem to do it. Restarting HA certainly does not.

**Comment by YorkshireIoT** [comment]
On the integrations page in Home Assistant if you click on the 3 dots in the top right and go to application credentials you can manage and delete credentials there.

**Comment by Ivesvdf** [comment]
That fixed it, learned something new. Thanks! Closing as invalid.
