### ISSUE TITLE
Option - configure update interval

### ISSUE THREAD

**Issue by rafkan20** [YorkshireIoT/ha-google-fit#44]
### System Health details

Home Assistant 2023.4.6
Supervisor 2023.04.1
Operating System 10.1
Interfejs użytkownika: 20230411.1 - latest
Ha-google-fit: v0.2.0-b4

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/YorkshireIoT/ha-google-fit/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Hi @YorkshireIoT.
After updating the add-on to v0.2.0 Beta 4, the "Configure" tab appears.

![jazz](https://images92.fotosik.pl/661/b5bd9591f4844d0c.jpg)

As you can see there is no description. It is possible to add a description of what the configuration applies to and in what units the digit is configured?

P.S. What was the data refresh time so far?

EDIT:
@YorkshireIoT you can start a thread on the Home Assistant forum? It will be easier to communicate.

### Reproduction steps

1. N/A
2.
3.
...

### Debug logs

```text
N/A
```

**Comment by YorkshireIoT** [comment]
R.e. the forum, what sort of things do you want to discuss?

GitHub has a built in discussions tab which I could enable and might be better suited.

**Comment by rafkan20** [comment]
> R.e. the forum, what sort of things do you want to discuss?

I meant the discussion about bugs that may appear in integration releases.



> GitHub has a built in discussions tab which I could enable and might be better suited.

I thought that on the official Home Assistant forum, the discussion about integration would reach more users.

**Comment by YorkshireIoT** [comment]
> > R.e. the forum, what sort of things do you want to discuss?
> 
> I meant the discussion about bugs that may appear in integration releases.
> 
> > GitHub has a built in discussions tab which I could enable and might be better suited.
> 
> I thought that on the official Home Assistant forum, the discussion about integration would reach more users.

I've started a new topic here: https://community.home-assistant.io/t/new-google-fit-ui-based-integration-yorkshireiot/565807?u=yorkshire_iot
