### ISSUE TITLE
Not Show Integration

### ISSUE THREAD

**Issue by gamajunior** [YorkshireIoT/ha-google-fit#52]
### System Health details

I did the installation and the sensors wouldn't update, I removed everything and remade it, but now it doesn't show the integration anymore.

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/YorkshireIoT/ha-google-fit/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

![image](https://github.com/YorkshireIoT/ha-google-fit/assets/78893093/e2b741b6-16ae-4567-9c6f-cd3c3e08de7c)

### Reproduction steps

1. desintall
2. reinstall  to zero
3.
...

### Debug logs

```text
no
```

**Comment by gamajunior** [comment]
Logger: googleapiclient.http
Source: custom_components/google_fit/config_flow.py:96
Integration: Google Fit ([documentation](https://github.com/YorkshireIoT/ha-google-fit), [issues](https://github.com/YorkshireIoT/ha-google-fit/issues))
First occurred: 02:27:55 (1 occurrences)
Last logged: 02:27:55

Encountered 403 Forbidden with reason "accessNotConfigured

**Comment by YorkshireIoT** [comment]
Hi @gamajunior,

Can you add which version you're on please? If you're not on the latest, can you update as well.

Can you also double check you have enable fit API access for your Google developer project, and double check the settings given in the instructions.

After this can you remove your credentials and integration (see https://github.com/YorkshireIoT/ha-google-fit#reconfiguring-badly-configured-credentials) and then try the setup again.

Thanks

**Comment by mrdunu** [comment]
You need to enable the Fitness API
https://console.cloud.google.com/marketplace/product/google/fitness.googleapis.com

**Comment by YorkshireIoT** [comment]
It's now been over a month with no response. Closing this issue down.

Please comment on this explaining why it is still an issue and I'll reopen.
