### ISSUE TITLE
Add sensor oxygen saturation

### ISSUE THREAD

**Issue by rafkan20** [YorkshireIoT/ha-google-fit#53]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/YorkshireIoT/ha-google-fit/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Please add oxygen saturation sensor.
New scope:
https://developers.google.com/fit/datatypes/health?hl=pl#oxygen_saturation

### Describe the solution you'd like

.

### Describe alternatives you've considered

.

### Additional context

.

**Comment by caohuongls** [comment]
I also think need to add this sensor. Many smartwatch now support this to sync with google fit

**Comment by YorkshireIoT** [comment]
Hi @caohuongls,

If you'd like a new sensor like BMI can you open up a new issue like this as this issue will only be dedicated to adding Oxygen Saturation sensors.

Thanks
