### ISSUE TITLE
Add info to message box when integration configuration fails

### ISSUE THREAD

**Issue by Hadatko** [YorkshireIoT/ha-google-fit#67]
## System Information

version | core-2023.6.3
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.4
os_name | Linux
os_version | 6.1.21-v8+
arch | aarch64
timezone | Europe/Prague
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4938
Installed Version | 1.32.1
Stage | running
Available Repositories | 1264
Downloaded Repositories | 20

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 3

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Debian GNU/Linux 11 (bullseye)
-- | --
update_channel | stable
supervisor_version | supervisor-2023.06.4
agent_version | 1.3.0
docker_version | 24.0.2
disk_total | 234.5 GB
disk_used | 51.4 GB
healthy | true
supported | failed to load: Unsupported
supervisor_api | ok
version_api | ok
installed_addons | Node-RED (14.2.2), Mosquitto broker (6.2.1), Zigbee2MQTT (1.32.0-2), File editor (5.6.0), Advanced SSH & Web Terminal (15.0.2), Alsa & PulseAudio Fix (3.4.1), Home Assistant Google Drive Backup (0.111.1), TasmoAdmin (0.24.4), Grafana (8.3.0), Duck DNS (1.15.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 12
views | 15
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | June 28, 2023 at 12:42
-- | --
current_recorder_run | July 2, 2023 at 11:00
estimated_db_size | 169.19 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/YorkshireIoT/ha-google-fit/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Originaly i was trying to use old implementation (https://github.com/cyberjunky/home-assistant-google_fit/issues/34).
Then i moved to this one and fixed my issue with credentials.
But after that empty dialog appeared and integration was not added to the list of integrations
![image](https://github.com/YorkshireIoT/ha-google-fit/assets/13130700/4a431c27-ac9f-467a-9f5d-a9a1bca17a05)

### Reproduction steps

1. Downloading current version in HACS.
2. Adding integration with correct creditionals.
3. Allow integration in same google email account

### Debug logs

```text
This error originated from a custom integration.

Logger: custom_components.google_fit.config_flow
Source: custom_components/google_fit/config_flow.py:104
Integration: Google Fit (documentation, issues)
First occurred: 11:01:45 (2 occurrences)
Last logged: 12:28:52

API Access Error: Fitness API has not been used in project 1063492990949 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/fitness.googleapis.com/overview?project=1063492990949 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
```

**Comment by Hadatko** [comment]
I was able to solve this issue. But creating issue to let you know:
I had to enable Fitness API which i didn't noticed in readme (only gmail API). Maybe i missed it, but if not it should be great to add it into readme.

**Comment by Hadatko** [comment]
Actually it showed up that i didn't read this sentence to the end: 
Instead, follow the instruction in the Official home Assistant Docs for [Google Mail](https://next.home-assistant.io/integrations/google_mail/) under the "Generate Client ID and Client Secret" section, replacing instructions for 'Gmail API' with *'Fit API'*

**Comment by Hadatko** [comment]
@YorkshireIoT are you able to improve post dialog scene when fit API is not enabled?

**Comment by YorkshireIoT** [comment]
@Hadatko, I would link it should be possible. If I can do a nice, detailed error in the logs like:
```
API Access Error: Fitness API has not been used in project 1063492990949 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/fitness.googleapis.com/overview?project=1063492990949 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
```
You would link I should be able to improve the message you get when it fails.
