### ISSUE TITLE
Add Sleep Sensor

### ISSUE THREAD

**Issue by YorkshireIoT** [YorkshireIoT/ha-google-fit#7]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/YorkshireIoT/ha-google-fit/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

N/A

### Describe the solution you'd like

Integration of the Google Fit Sleep data. Documentation describing how to get and use the data is described in:

- https://developers.google.com/fit/scenarios/read-sleep-data
- https://developers.google.com/fit/datatypes/health#sleep

This would update the permission scope of the integration by adding the new scope:
`https://www.googleapis.com/auth/fitness.sleep.read`

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by milandzuris** [comment]
This is i need very

**Comment by YorkshireIoT** [comment]
There's a beta release out for this @milandzuris if you want to try it out before the next full release

**Comment by milandzuris** [comment]
> There's a beta release out for this @milandzuris if you want to try it out before the next full release

![Screenshot_20230410_155127_Home Assistant.jpg](https://user-images.githubusercontent.com/42905545/230914630-8412ac70-eba7-4a0f-b935-8521f20a908f.jpg)

**Comment by milandzuris** [comment]
I think is better without Daily and past24h details in sensor, and look better, in the app is the same without this details.

![image](https://user-images.githubusercontent.com/42905545/230930008-f2f658af-e9ea-4c59-86b6-07de30c4355c.png)
![image](https://user-images.githubusercontent.com/42905545/230960261-fa905168-3198-4916-9f0c-ebeaddc6e34e.png)

**Comment by YorkshireIoT** [comment]
> I think is better without Daily and past24h details in sensor, and look better, in the app is the same without this details.
> 
> ![image](https://user-images.githubusercontent.com/42905545/230930008-f2f658af-e9ea-4c59-86b6-07de30c4355c.png) ![image](https://user-images.githubusercontent.com/42905545/230960697-1b3aadec-e32f-4ad9-bcd3-b705eb732e58.png)

I've added #37 to shorten the sleep sensor names. I won't be shortener the others as this would be a breaking change to sensors that might mess up people's automations + dashboards. The sleep addition is still just a beta release however so I'm happy to shorten them.
