### ISSUE TITLE
Add Blood Glucose Sensor

### ISSUE THREAD

**Issue by lunarok** [YorkshireIoT/ha-google-fit#71]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/YorkshireIoT/ha-google-fit/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Not related to a problem, it's pure enhancement. But the existing work is already great a big thanks.

### Describe the solution you'd like

This integration is great, love the fact compared to previous one that all entities are linked on one equipment (something that is missing in some official integrations like Withings)

I have one very important health data that is missing today : Blood Glucose (as diabetic, it's the main one for me) And I will appreciate a lot to have it added.

### Describe alternatives you've considered

Will try to read and understand the code, and Google Fit dataset to help on providing additional sensors

Some other sensors are missing also, any feature planned to be able to select additional optional sensors that user want to create ?

### Additional context

No idea if from read, the write is complex to implement, but being able to register some activity from HA will be great option in future (I have reminders send for workouts and walks, so could continue by registering the workout automaticly)

**Comment by YorkshireIoT** [comment]
Hi @lunarok,

I can definitely try add Blood Glucose as an additional sensor but it would just be read access. I have no plans to make any of the sensors in this integration have write access so Home Assistant itself can write back to the Fit database.

Thanks

**Comment by lunarok** [comment]
Hi,

Well, already other sensors will be great.
I try adding glucose based on API doc and your code, I get those :

const.py
    GoogleFitSensorDescription(
        key="google_fit",
        name="Blood Glucose",
        icon="mdi:water",
        native_unit_of_measurement="mmol/L",
        state_class=SensorStateClass.MEASUREMENT,
        device_class=None,
        source="derived:com.google.blood_glucose:com.google.android.gms:merged",
        data_key="bloodGlucose",
    ),

blood glucose is in an additional scope of API so need to add also :
https://www.googleapis.com/auth/fitness.blood_glucose.read

in api_types I add bloodGlucose to FintnessData in dictonary, for api.py I add bloodGlucose in parse_point and init

When adding the integration in HA, I see that oauth screen is asking consent including the glucose API
The sensor is created but not filled, some "error when retrieving a log entry :3", in french :
Erreur lors de la récupération d'une entrée du journal: 3

Still trying to understand what is not working.

Oh, and for glucose, their is some attribute of entries that could matter for some people (mainly if measurument is done before or after eating) Other sensors could benefit also of a way to be able to get additional details aside of value and add them as attribute in HA (blood pressure I think Google Fit expose if it's taken lie down or sit down)

**Comment by lunarok** [comment]
Ok, my wrong, didnt update the integration in HACS after updating source of fork
I get it working, all sensors are showing results including Glucose, will be able to propose a PR

**Comment by lunarok** [comment]
PR : https://github.com/YorkshireIoT/ha-google-fit/pull/74

**Comment by YorkshireIoT** [comment]
Closed by PR#74
