### ISSUE TITLE
Google Fit integration could not be installed

### ISSUE THREAD

**Issue by XalaTheShepard** [YorkshireIoT/ha-google-fit#81]
## System Information

version | core-2023.7.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.4
os_name | Linux
os_version | 6.1.34
arch | x86_64
timezone | Europe/Brussels
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4993
Installed Version | 1.32.1
Stage | running
Available Repositories | 1331
Downloaded Repositories | 50

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 43

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.3
-- | --
update_channel | stable
supervisor_version | supervisor-2023.07.1
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 97.7 GB
disk_used | 20.7 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Duck DNS (1.15.0), File editor (5.6.0), AppDaemon (0.13.3), Spotify Connect (0.12.4), Terminal & SSH (9.7.1), Home Assistant Google Drive Backup (0.111.1), Node-RED (14.4.2), AdGuard Home (4.8.12), Samba share (10.0.2), Studio Code Server (5.9.0), UniFi Network Application (2.7.0), Mosquitto broker (6.2.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 16
views | 21
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | July 14, 2023 at 7:53 AM
-- | --
current_recorder_run | July 23, 2023 at 4:32 PM
estimated_db_size | 476.68 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/YorkshireIoT/ha-google-fit/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Good evening, 

I was able to install the Google Fit custom component into HACS. Afterwards, I have enabled in the Cloud console the Fitness API. 
When I select Google Fit in the integrations page to install, it keeps on loading for 5 minutes and gives the error below:

Error
Config flow could not be loaded: <html> <head><title>405 Not Allowed</title></head> <body> <center><h1>405 Not Allowed</h1></center> <hr><center>nginx</center> </body> </html>      

Because the custom component cannot be installed as an integration, I have no debug logs.

### Reproduction steps

1. Install Google Fit custom component
2. Enable Fitness API
3. Try to install the Google Fit custom component in the integration page

### Debug logs

```text
Not available, as the custom component could not be installed as an integration.
```

**Comment by YorkshireIoT** [comment]
Hi @XalaTheShepard, what version of the integration are you on?

**Comment by XalaTheShepard** [comment]
Dear YorkshireIoT, I have version 1.1.0 of the custom component installed.

Many thanks for looking into the issue.

**Comment by XalaTheShepard** [comment]
Dear YorkshireIoT, I don't even get the screen where it requests the clientID and the client secret. I wonder if it has to do with another Google Fit custom component, that I have tried before (the one of Cyberjunky). I tried that one before, but got a 401 error. It also seemed no longer maintained. In one of the issues, I have found the link to your custom component which is still maintained and solved that issue.

**Comment by XalaTheShepard** [comment]
I still don't know what the issue was, but I just noticed version 2.0.0 was availiable. I have updated the custom component and now I was able to complete my credentials and link to my account. Thank you very much for the support. Kind regards

**Comment by YorkshireIoT** [comment]
Thanks for the update @XalaTheShepard and glad to here it's working.

There wasn't any noteworthy change from v1.1.0 to v2.0.0 so I can only guess that the download from HACs could've been corrupted (possibly caused by the alternative Google Fit custom component)
