### ISSUE TITLE
Not able to find this in HACS

### ISSUE THREAD

**Issue by EvilCartyen** [YorkshireIoT/ha-google-fit#87]
### System Health details

- not a system health issue -

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/YorkshireIoT/ha-google-fit/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Running HACS 1.32.1 on the following...

Home Assistant 2023.8.1 
Supervisor 2023.07.1 
Operating System 10.4 
Frontend 20230802.0 - latest 

...and not finding this project in the HACS Integrations browser - which is a shame, as I'd like to try it out :)

### Reproduction steps

1. Open a HA instance with HACS 1.32.1 installed
2. Open HACS and click 'Explore and download repositories'
3. Search for this project by typing 'Google Fit'
4. Fail :(

### Debug logs

```text
-
```

**Comment by YorkshireIoT** [comment]
Hi @EvilCartyen,

This is still a custom repo so please follow these instructions: https://github.com/YorkshireIoT/ha-google-fit#custom-repository

**Comment by EvilCartyen** [comment]
Hmm, OK thank you 🙂 I was sure the documentation mentioned HACS and how to
install. I will wait until it's released there then.

Thanks!

**Comment by YorkshireIoT** [comment]
Just to clarify, it is still possible to install through HACs.

If you click the link it will show you how to install through HACs as a custom component
