### ISSUE TITLE
Where can I find "Energy expended" from Google Fit app? "Calories Burnt Daily" seems to be off.

### ISSUE THREAD

**Issue by Defozo** [YorkshireIoT/ha-google-fit#98]
[Calories burned - Documentation](https://developers.google.com/fit/datatypes/activity#calories_burned)

Google Fit app:
Energy expended on August 31: 2102 Cal

Home Assistant:
Last `Energy Burnt Daily` on August 31: 1707.79 kcal

**Comment by YorkshireIoT** [comment]
Hi @Defozo, there is a slight delay between data showing on your Google Fit app and that data then being available to developers in the cloud to access via their API (which is what this integration uses).

In my experience this can be 30-60 minutes but I've also noticed (at least on my device) that data is not uploaded when on mobile data, only WiFi.

Could you check this again, noting down timings, and seeing if this could apply in your case?

**Comment by YorkshireIoT** [comment]
Closing this down now, please re-open with the timings requested above if you still have a problem
